"""
=============================================================================
PAPER TRADER — Sandbox Live Testing
=============================================================================
Runs hypotheses that have passed out-of-sample backtesting (PAPER_TRADING status)
alongside the live system, but WITHOUT executing real trades.

It monitors the signals generated by these experimental strategies in real-time
and records the hypothetical outcomes.

Pipeline position:
  BacktestValidator → [PAPER TRADER] → Live Approval
=============================================================================
"""

import pandas as pd
from typing import Dict, Any, List
from datetime import datetime

from data.hypothesis_generator import HypothesisManager


class PaperTrader:
    """
    Simulates live trading for experimental strategies.
    """

    def __init__(self, data_dir: str = None, min_paper_trades: int = 20, min_win_rate: float = 60.0):
        self.hyp_manager = HypothesisManager(pipeline_dir=f"{data_dir}/strategy_pipeline" if data_dir else None)
        
        self.min_paper_trades = min_paper_trades
        self.min_win_rate = min_win_rate

    def evaluate_live_signals(self, symbol: str, experimental_signals: List[Dict], current_price: float):
        """
        Takes signals generated by experimental strategies in the current cycle
        and records them as pending paper trades.
        """
        # In a real implementation, this would save pending trades to a database
        # and check them on subsequent cycles to see if they hit TP or SL.
        pass
        
    def check_graduations(self):
        """
        Evaluates the paper trading results of all hypotheses in PAPER_TRADING status.
        If they meet the criteria, they are marked as APPROVED.
        """
        paper_trading_hyps = self.hyp_manager.get_by_status("PAPER_TRADING")
        
        for hyp in paper_trading_hyps:
            results = hyp.paper_trade_results
            
            if not results:
                continue
                
            trades_completed = results.get("trades_completed", 0)
            win_rate = results.get("win_rate_pct", 0)
            
            if trades_completed >= self.min_paper_trades:
                if win_rate >= self.min_win_rate:
                    # Graduation!
                    self.hyp_manager.update_status(
                        hyp.hypothesis_id, 
                        "APPROVED", 
                        f"Passed paper trading with {win_rate:.1f}% WR over {trades_completed} trades."
                    )
                else:
                    # Failed paper trading
                    self.hyp_manager.update_status(
                        hyp.hypothesis_id, 
                        "REJECTED", 
                        f"Failed paper trading: {win_rate:.1f}% WR (< {self.min_win_rate}% threshold)."
                    )
